version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:
  docs:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: good8815585/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media/
  frontend:
    image: good8815585/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: good8815585/foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media/
      - docs:/usr/share/nginx/html/api/docs
    ports:
      - 8000:80