TAG_NAME_MAX_LENGTH = 50
TAG_COLOR_MAX_LENGTH = 7

INGREDIENT_NAME_MAX_LENGTH = 100
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 10

RECIPE_NAME_MAX_LENGTH = 200
RECIPE_IMAGE_UPLOAD_TO = 'recipe_images/'

RECIPE_INGREDIENT_AMOUNT_MIN = 1
RECIPE_INGREDIENT_AMOUNT_MAX = 10000
