# Generated by Django 4.2.7 on 2023-12-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_userfavoriterecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
